version: "3.7"
services:
  bp2023:
    build: .
    container_name: bp2023
    ports:
      - "5001:5001"
    depends_on:
      - mysql
      - redis
    networks:
      - bpnet
    restart: always
  redis:
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - bpnet
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=book
      - MYSQL_USER=book
      - MYSQL_PASSWORD=book123
      - MYSQL_ROOT_PASSWORD=book123
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - bpnet
volumes:
  mysql:
networks:
  bpnet:
    driver: bridge